name: Flask URLTesting CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest URLTesting.TransferAddress.app_unit_test


      - name: Debug tree & path
        run: |
          pwd
          ls -la
          ls -la URLTesting || true
          ls -la URLTesting/TransferAddress || true
          python - <<'PY'
          import sys, os
          print("PYTHONPATH =", os.environ.get("PYTHONPATH"))
          print("sys.path[0] =", sys.path[0])
          import importlib
          m = importlib.import_module("URLTesting.app")
          print("Imported:", m)
          PY
